### ISSUE TITLE
Consistent log output

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/snake-pp#6]
Since the terminal output is shown beside the sdl window when running the release elsewhere,
it would be more professional when the terminal output is consistent.

## rules suggestion
- english language
- use `LOGI()` or `LOGD()`
- always use a prefix e.g. `game:` so origin is more clear

## tasks
- [x] maybe add ~`LOGW()`?~ (Added `LOGE()`) 
- [x] re-evaluate log level (move actual debug output to `LOGD()`)
- [ ] apply below notes in current log example  - leaderboard.c
- [x] apply below notes in current log example  - food.c
- [ ] apply below notes in current log example  - file.c

## current typical output:
``` log
In first loop                          ### prefix, move to debug / make more clear?
[I] game: initializing game...
[I] map: loading map 'default':
[I] food: placed food at x=3, y=6 (took 1 = 1*1 tries)
[I] game: placed initial food at x=3, y=6                              ### remove or move above place command
[I] game: picked up food at x=3 y=6 -> growing, placing food
[I] sound: initialized SDL audio
[I] food: placed food at x=5, y=3 (took 1 = 1*1 tries)                    ### fix tries calculation
[I] sound: playing file 'assets/sounds/eat-bite2.wav'                     ### sound to warn / debug level?
[I] game: entered portal i=0 at x=5, y=8 -> set head to x=7 y=1
[I] sound: playing file 'assets/sounds/portal3_in-out.wav'
[I] game: collided with wall or self! => show leaderboard             ### add log output when switching to menu state / certain menu?
[I] sound: playing file 'assets/sounds/crash_rock-cinematic.wav'
[I] Spielergebnis wurde erfolgreich in die Binaerdatei gespeichert.   ### language, prefix
[I] Datensaetze in Datei: 12                                          ### language, prefix
[I] score: 53  name: testuser  schwierigkeit: 1  map: default    ### add one line "leaderboard: printing scoreboardl
[I] score: 40  name: jonny  schwierigkeit: 3  map: empty         ### looks fine, maybe add indentation so it belongs to "printing scoreboard"
[I] score: 30  name: jonny  schwierigkeit: 3  map: empty
[I] score: 24  name: 1  schwierigkeit: 3  map: intermediate
[I] score: 22  name: jonny  schwierigkeit: 2  map: empty  
```
